### ISSUE TITLE
Builder role does not appear to implement AAP registration

### ISSUE THREAD

**Issue by zjpeterson** [redhat-cop/infra.osbuild#127]
Setting the `builder_aap_*`  variables described in the documentation doesn't produce anything new in the resulting kickstart for me. I see the template to do it at  `roles/builder/templates/auto_register_aap.j2`, and if I grab that myself and add it to my kickstart in a `%post` block after the role runs, it does work as expected, should just run within the role.

**Comment by resoluteCoder** [comment]
@zjpeterson When adding the `builder_aap_*` variables did you also add `- "{{ lookup('ansible.builtin.template', '../templates/auto_register_aap.j2') }}"` as a list item for the `builder_kickstart_post` variable described here: https://github.com/redhat-cop/infra.osbuild/tree/main/roles/builder#builder_kickstart_post

I ask because I did the same thing while trying to reproduce this bug. 

There seems to be another requirement to use those variables that are provided. This in my opinion isn't optimal for the user. The user should be able to define variables and not worry about anything else. 

I can add the necessary changes to make sure only `aap` vars are needed for the aap portion to be injected into the kickstart file.
